import type { Metadata } from "next";
import { Onest } from "next/font/google";
import "./globals.css";

const onest = Onest({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Lenovo Xt80 Bluetooth 5.3 - Audífonos Deportivos Inalámbricos",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${onest.className} bg-[#f7f7f7]`} >{children}</body>
    </html>
  );
}
